WIP: Fix more than 64 cpu
Tencent/ncnn pull request #1973
Opened 2020-07-27 14:07 UTC by tpoisonooo

尝试修复 CPU 个数大于 64 时设置亲和力失败的问题。

a. 如果是 linux/unix 流派系统，引用系统库`sched.h`的`cpu_set_t`;
b. 如果是 windows 系统，自己糙一个 `struct cpu_set_t`。装作 64 核 windows 跑 ncnn 的场景不存在...

work in progress.

2020-08-08 16:31 UTC, nihui commented on src/cpu.h
> +
Linux 因为是纯C的项目，没有办法才 CPU_SET CPU_ZERO 这样
ncnn 做个 class CpuSet

2020-08-09 02:29 UTC, tpoisonooo commented on src/cpu.h
> +
你是说：
```
class CpuSet {
#if android or linux
调用系统的 cpu_set_t 相关的 CPU_SET 等
#else
糙自己的 cpu_set_t
#endif
};
```
对外提供不区分平台的接口？

2020-08-17 08:36 UTC, nihui commented on src/cpu.h
> +
move private block after the public block

2020-08-17 08:41 UTC, nihui commented on src/cpu.h
> +    }
These two functions are implementation-specific, and for internal use only.
Move them to protected block, and add related friend functions

2020-08-17 08:42 UTC, nihui commented on src/cpu.h
> +    unsigned long m_bits[CPU_SETSIZE / NCNN_NCPUBITS];
rename CPU_SETSIZE to NCNN_CPU_SETSIZE like how NCNN_NCPUBITS does

2020-08-17 08:43 UTC, nihui commented on src/cpu.h
> +int set_cpu_thread_affinity(CpuSet thread_affinity_mask);
```const CpuSet&```

2020-08-17 08:44 UTC, nihui commented on src/cpu.h
> +CpuSet get_cpu_thread_affinity_mask(int powersave);
The global affinity masks are always defined, return ```const CpuSet&```

2020-08-17 08:45 UTC, nihui commented on src/cpu.h
> +
The constructor is missing

2020-09-03 03:13 UTC, tpoisonooo commented
done.

2020-09-03 10:41 UTC, tpoisonooo commented
@nihui  重新触发一下  CI ？ 我就merge 一下 code format 就不行了...

2020-09-03 10:44 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=1973) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=1973) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tpoisonooo<br/>:x: restyled-commits<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=1973) it.</sub>

2020-09-03 11:10 UTC, tpoisonooo commented
close 大法好！

2020-09-04 03:16 UTC, tpoisonooo commented
@nihui  CI 里面 
```
The command "eval git clone --depth=50 --branch=restyled/pull-1973 https://github.com/Tencent/ncnn.git Tencent/ncnn " failed. Retrying, 2 of 3.

求看一下。

2020-09-05 03:27 UTC, nihui requested changes

2020-09-05 03:27 UTC, nihui commented on src/cpu.cpp
> +    CpuSet thread_affinity_mask = get_cpu_thread_affinity_mask(powersave);
const CpuSet&

2020-09-05 03:27 UTC, nihui commented on src/cpu.h
> +} // namespace ncnn
这些定义似乎并没有哪里用到了

2020-09-05 03:27 UTC, nihui commented on src/cpu.h
> +#endif
这里直接调用 zero()

2020-09-05 03:27 UTC, nihui commented on src/cpu.h
> +    unsigned long m_bits[NCNN_CPU_SETSIZE / NCNN_NCPUBITS] = {0};
如果 android / linux 以外的平台都是没有用的，就没有必要用 m_bits 模拟这个了

2020-09-07 06:23 UTC, nihui requested changes

2020-09-07 06:23 UTC, nihui commented on src/cpu.h
> +#endif
duplicated includes

2020-09-07 08:36 UTC, closed without merging