Support remove libstdc++ denpendency
Tencent/ncnn pull request #2030
Opened 2020-08-21 11:58 UTC by nullptr-leo

build:
```
mkdir -p build && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/host-c.gcc.toolchain.cmake -DNCNN_SIMPLESTL=ON ..
make -j128
```

w/ libstdc++.so:
```
-rw-rw-r-- 1 null null 4030840 Aug 22 14:13 libncnn.a
-rwxrwxr-x 1 null null 2334408 Aug 22 14:13 benchncnn*

$ readelf -a benchncnn | grep NEE

 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libmvec.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

w/o libstdc++.so:
```
-rw-rw-r-- 1 null null 3584322 Aug 22 14:15 libncnn.a
-rwxrwxr-x 1 null null 2221592 Aug 22 14:15 benchncnn*

$ readelf -a benchncnn | grep NEE

 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
```

squeezenet:
```
./squeezenet panda.jpg
max 388 = 0.999143
```

2020-08-24 07:23 UTC, nullptr-leo commented
@nihui done. restyles 搞不定 :(

2020-08-24 07:26 UTC, nihui commented
restyle无所谓吧……

2020-08-25 06:25 UTC, nihui requested changes

2020-08-25 06:25 UTC, nihui commented on src/allocator.cpp
> +        for (auto it = payouts.begin(); it != payouts.end(); ++it)
auto 关键字要求 c++11
如果这里不方便实现 std::list iterator 类型的话，用宏区分代码
```
#if NCNN_SIMPLESTL
    // use simplestl type
#else
    // use the orignal stl iterator
#endif
```

2020-08-25 06:25 UTC, nihui commented on src/CMakeLists.txt
> +    simplestl.cpp
```
if(NCNN_SIMPLESTL)
    list(APPEND ncnn_SRCS simplestl.cpp)
endif()
```

2020-08-25 06:25 UTC, nihui commented on src/simplestl.h
> +    node* next_ = nullptr;
move initializer to constructor

2020-08-25 06:25 UTC, nihui commented on src/simplestl.h
> +    node<T>* curr_ = nullptr;
move initializer to constructor

2020-08-25 06:25 UTC, nihui commented on src/simplestl.h
> +    size_t count_ = 0;
move initializer to constructor

2020-08-27 09:41 UTC, nullptr-leo commented on src/CMakeLists.txt
> +    simplestl.cpp
这里是参照 mat_pixel 的方式，cpp 里面全部用宏包着

2020-08-27 11:33 UTC, nihui commented on src/CMakeLists.txt
> +    simplestl.cpp
好吧，也行 w

2020-08-27 11:44 UTC, nihui requested changes

2020-08-27 11:44 UTC, nihui commented on src/CMakeLists.txt
> +    target_link_libraries(ncnn PUBLIC -lm)
why ```-lm``` instead of ```m``` ?

2020-08-27 11:44 UTC, nihui commented on src/CMakeLists.txt
> +        target_link_libraries(ncnn PUBLIC -lgcc)
why ```-lgcc``` instead of ```gcc``` ?

2020-08-28 01:20 UTC, merged

2020-08-28 01:21 UTC, nihui commented
thanks!p