Fix yolov4 example bgr2rgb
Tencent/ncnn pull request #2051
Opened 2020-08-31 12:20 UTC by MarsTechHAN

2020-08-31 12:53 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2051) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2051) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2051) it.</sub>

2020-09-01 06:16 UTC, nihui requested changes

2020-09-01 06:16 UTC, nihui commented on examples/CMakeLists.txt
> +    find_package(OpenCV QUIET COMPONENTS core highgui imgproc videoio)
This line is for opencv 2.x, videoio is not needed as highgui is enough

2020-09-01 06:16 UTC, nihui commented on examples/yolov4.cpp
> +#include <opencv2/videoio/videoio.hpp>
There is no videoio in opencv 2.x
guard with version macro
```
CV_MAJOR_VERSION
CV_MINOR_VERSION
```

2020-09-01 06:16 UTC, nihui commented on examples/yolov4.cpp
> +#include <chrono>
ncnn benchmark.h has the necessary timestamp functions
Besides, c++11 is not mandatory when building with opencv 2.x

2020-09-01 06:16 UTC, nihui commented on examples/yolov4.cpp
> +    yolov4->opt.use_vulkan_compute = true; ////You need to compile with libvulkan for multi thread support
////You need to compile with libvulkan for gpu support

2020-09-01 06:16 UTC, nihui commented on examples/yolov4.cpp
> +        detect_yolov4(frame, objects, target_size, &yolov4); //Creat an extractor and run detection
// Create

2020-09-01 08:30 UTC, nihui approved these changes

2020-09-01 08:31 UTC, merged

2020-09-01 08:31 UTC, nihui commented
hanxiao yes !