Improve build instructions
Tencent/ncnn pull request #2174
Opened 2020-10-05 21:08 UTC by baryluk

* Merge Linux stuff into one section.
* Provide better info on dependencies
* Provide easier to use instruction for Debian / Ubuntu for native and cross-compile builds
* Capitalize Sentence and put proper punctation.
* Use backticks where appropiate
* Move Hisilicon instruction together with Arm crosscompiling
* Add information how to verify the Vulkan installation on Linux
* Change how to launch examples so it is easier (no copying needed or external resources)
* Add info about benchmark and how to test it on GPU or CPU
* Use `$(nproc)` where appropriate.
* Put some paths in quotes, in case they contain spaces or other weird characters (coma, semicolon, colon, etc).
* Remove some extremely obvious pieces that every developer usually knows.
* Use newer Vulkan SDK in instructions for Linux
* Get rid of `<ncnn-root-dir>`, and just use `ncnn`. It is what git clone does. And any developer will know how to change it if they choose to do it differently.

2020-10-05 21:09 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2174) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2174) it.</sub>

2020-10-06 10:56 UTC, nihui requested changes

2020-10-06 10:56 UTC, nihui commented on docs/how-to-build/how-to-build.md
Apply the link changes in https://github.com/Tencent/ncnn/blob/master/README.md

2020-10-09 09:02 UTC, nihui approved these changes

2020-10-09 15:55 UTC, merged