fix mat_pixel_android.cpp shadowed variables warning
Tencent/ncnn pull request #2447
Opened 2020-12-14 13:14 UTC by zchrissirhcz

2020-12-14 16:19 UTC, nihui requested changes

2020-12-14 16:19 UTC, nihui commented on src/mat_pixel_android.cpp
pass _data to to_pixels_resize()

2020-12-14 16:19 UTC, nihui commented on src/mat_pixel_android.cpp
> +        _elempack = 4;
if _elempack is never used, remove it

2020-12-15 01:40 UTC, zchrissirhcz commented
Thanks for reviewing. Modified as recommended. (Also learn git pull && git rebase operation from this PR.)

2020-12-15 07:10 UTC, nihui approved these changes

2020-12-15 07:10 UTC, merged