add cocospod surpport for ncnn
Tencent/ncnn pull request #2670
Opened 2021-02-08 07:15 UTC by DaChengTechnology

add release pod ci and Mac&&iOS podspec

2021-02-08 14:53 UTC, DaChengTechnology commented
fixed Mac pod

2021-02-09 10:57 UTC, DaChengTechnology commented
if you marged this pull request,then give me a url for iOS_openmp_bitcode after run the realse_pod.yml. then I`ll update dpcument and examples @nihui

2021-02-09 16:47 UTC, DaChengTechnology commented
test the cocoapods publish is passed

2021-02-09 16:48 UTC, DaChengTechnology commented
pod search NCNN

2021-02-10 02:32 UTC, nihui requested changes

2021-02-10 02:32 UTC, nihui commented on NCNN_IOS.podspec
> +  spec.platform     = :ios, "9.0"
duplicated license and platform

2021-02-10 02:32 UTC, nihui commented on NCNN_MAC.podspec
> +  spec.platform     = :osx, "10.12"
duplicated license and platform

2021-02-10 08:45 UTC, DaChengTechnology commented
it is fixed

2021-02-12 17:54 UTC, closed without merging