Use RVV spec 0.7.1 for C906.
Tencent/ncnn pull request #2868
Opened 2021-04-25 03:44 UTC by xianyi

Use RVV spec 0.7.1 for C906.

Change the compile flags in C906 toolchian file.

2021-04-25 03:44 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2868) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2868) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2868) it.</sub>

2021-04-26 02:02 UTC, nihui commented
depend on riscv toolchain updates https://github.com/Tencent/ncnn/pull/2872

2021-04-26 06:15 UTC, nihui requested changes

2021-04-26 06:15 UTC, nihui commented on src/layer/riscv/clip_riscv.cpp
> +#endif
please fix the coding style
use space for indentation

2021-04-26 15:48 UTC, BUG1989 approved these changes
LGTM!

2021-04-26 23:26 UTC, nihui approved these changes

2021-04-26 23:27 UTC, merged

2021-04-26 23:27 UTC, nihui commented
thanks for your contribution!