fix invalid read for yuv420sp2rgb on arm32
Tencent/ncnn pull request #3066
Opened 2021-07-10 13:41 UTC by zchrissirhcz

Hi Nihui

This PR try to fix "invalid read" `yuv420sp2rgb` and `yuv420sp2rgb_nv12`, for android arm32 platform assembly, for the last iter.

## Reproduce
I use these steps:

1. manually interpret arm32 assembly to neon intrinsics
2. put these intrinsics under arm64 code region
3. turn on Address Sanitizer and run on android arm64,  test phone is MI11 with Android 11
4. During runtime, Asan complains 

## Code
I  manually interpret line by line:
```c++
            // "pld        [%3, #128]          \n"
            // "vld1.u8    {d2}, [%3]!         \n"
            /// load vuvuvuvu (8 uchar)
            int8x8_t d2 = vreinterpret_s8_u8(vld1_u8(vuptr));
            vuptr += 8;

            // "vsub.s8    d2, d2, %12         \n"
            /// each v = v - 128
            /// each u = u - 128
            d2 = vsub_s8(d2, _v128);
            
            while (true)
            {
                // "0:                             \n"
                // "pld        [%1, #128]          \n"
                // "vld1.u8    {d0}, [%1]!         \n"
                /// load yyyyyyyy (8 uchar), the 1st line of Y plane
                uint8x8_t d0 = vld1_u8(yptr0);
                yptr0 += 8;

                // "pld        [%2, #128]          \n"
                // "vld1.u8    {d1}, [%2]!         \n"
                /// load yyyyyyyy (8 uchar), the 2nd line of Y plane
                uint8x8_t d1 = vld1_u8(yptr1);
                yptr1 += 8;

                // "vshll.u8   q2, d0, #6          \n"
                /// q2[i] = d0[i] << 6, and q2[i]=u16, d0[i]=u8
                uint16x8_t q2 = vshll_n_u8(d0, 6);

                // "vorr       d3, d2, d2          \n"
                /// d3 as copy of d2
                int8x8_t d3 = vorr_s16(d2, d2);

                // "vshll.u8   q3, d1, #6          \n"
                /// q3[i] = d1[i] << 6, and q3[i]=u16, d1[i]=u8
                uint16x8_t q3 = vshll_n_u8(d1, 6);

                // "vorr       q9, q2, q2          \n"
                /// q9 as copy of q2
                uint16x8_t q9 = vorrq_u16(q2, q2);

                // "vtrn.s8    d2, d3              \n"
                /// old:
                /// d2: 1 2 3 4 5 6 7 8
                /// d3: 1 2 3 4 5 6 7 8
                /// now:
                /// d2: 1 1 3 3 5 5 7 7
                /// d3: 2 2 4 4 6 6 8 8
                int8x8x2_t tmp = vtrn_s8(d2, d3);
                d2 = tmp.val[0];
                d3 = tmp.val[1];

                // "vorr       q11, q3, q3         \n"
                /// q11 as copy of q3
                uint16x8_t q11 = vorrq_u16(q3, q3);

                // "vmlsl.s8   q9, d2, %14         \n"
                /// q9[i] = q9[i] - d2[i] * _v46[i]
                q9 = vmlsl_s8(q9, d2, _v46);

                // "vorr       q8, q2, q2          \n"
                /// q8 as copy of q2
                uint16x8_t q8 = vorrq_u16(q2, q2);

                // "vmlsl.s8   q11, d2, %14        \n"
                /// q11[i] = q11[i] - d2[i] * _v46[i]
                q11 = vmlsl_s8(q11, d2, _v46);

                // "vorr       q10, q3, q3         \n"
                /// q10 as copy of q3
                uint16x8_t q10 = vorrq_u16(q3, q3);

                // "vmlal.s8   q8, d2, %13         \n"
                /// q8[i] = q8[i] - d2[i] * _v90[i]
                q8 = vmlal_s8(q8, d2, _v90);

                // "vmlal.s8   q2, d3, %16         \n"
                /// q2[i] = q2[i] - d3[i] * _v113[i]
                q2 = vmlal_s8(q2, d3, _v113);

                // "vmlal.s8   q10, d2, %13        \n"
                /// q10[i] = q10[i] - d2[i] * _v90[i]
                q10 = vmlal_s8(q10, d2, _v90);

                // "vmlsl.s8   q9, d3, %15         \n"
                /// q9[i] = q9[i] - d3[i] * _v22[i]
                q9 = vmlsl_s8(q9, d3, _v22);

                // "vmlal.s8   q3, d3, %16         \n"
                /// q3[i] = q3[i] - d3[i] * _v113[i]
                q3 = vmlal_s8(q3, d3, _v113);

                // "vmlsl.s8   q11, d3, %15        \n"
                /// q11[i] = q11[i] - d3[i] * _v22[i]
                q11 = vmlsl_s8(q11, d3, _v22);

                uint8x8x3_t d24_d25_d26;
                // "vqshrun.s16 d24, q8, #6        \n"
                /// d24[i] = q8[i] >> 6,   q8[i] as u16, d24[i] as u8
                d24_d25_d26.val[0] = vqshrun_n_s16(q8, 6);

                // "vqshrun.s16 d26, q2, #6        \n"
                /// d26[i] = q2[i] >> 6,   q2[i] as u16, d26[i] as u8
                d24_d25_d26.val[2] = vqshrun_n_s16(q2, 6);

                uint8x8x3_t d4_d5_d6;
                // "vqshrun.s16 d4, q10, #6        \n"
                /// d4[i] = q10[i] >> 6,   q10[i] as u16, d4[i] as u8
                d4_d5_d6.val[0] = vqshrun_n_s16(q10, 6);

                // "vqshrun.s16 d25, q9, #6        \n"
                /// d25[i] = q9[i] >> 6,   q9[i] as u16, d25[i] as u8
                d24_d25_d26.val[1] = vqshrun_n_s16(q9, 6);

                // "vqshrun.s16 d6, q3, #6         \n"
                /// d6[i] = q3[i] >> 6,    q3[i] as u16, d6[i] as u8
                d4_d5_d6.val[2] = vqshrun_n_s16(q3, 6);

                // "vqshrun.s16 d5, q11, #6        \n"
                /// d5[i] = q11[i] >> 6,   q11[i] as u16, d5[i] as u8
                d4_d5_d6.val[1] = vqshrun_n_s16(q11, 6);

                // "pld        [%3, #128]          \n"
                // "vld1.u8    {d2}, [%3]!         \n"
                /// load vuvuvuvu (8 uchar)
                d2 = vld1_u8(vuptr);
                vuptr += 8;

                // "subs       %0, #1              \n"
                nn--;

                // "vst3.u8    {d24-d26}, [%4]!    \n"
                /// rgb0 <-- rgbrgbrgb...rgb (24 uchar)
                vst3_u8(rgb0, d24_d25_d26);
                rgb0 += 24;

                // "vsub.s8    d2, d2, %12         \n"
                d2 = vsub_s8(d2, _v128);

                // "vst3.u8    {d4-d6}, [%5]!      \n"
                vst3_u8(rgb1, d4_d5_d6);
                rgb1 += 24;

                // "bne        0b                  \n"
                if (nn == 0) break;
            }
            // "sub        %3, #8              \n"
            vuptr -= 8;
```

## Run Output
```
(base) zz@localhost% ./android-arm64-run.sh  
android-arm64/testbed: 1 file pushed. 29.9 MB/s (1461072 bytes in 0.047s)
=================================================================
==29799==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00729a5ff800 at pc 0x005b3718ca90 bp 0x007fd3b03cf0 sp 0x007fd3b03ce8
READ of size 8 at 0x00729a5ff800 thread T0
    #0 0x5b3718ca8c  (/data/local/tmp/testbed+0x25a8c)
    #1 0x5b37187d14  (/data/local/tmp/testbed+0x20d14)
    #2 0x731dc6a054  (/apex/com.android.runtime/lib64/bionic/libc.so+0x85054)

0x00729a5ff800 is located 0 bytes to the right of 49766400-byte region [0x007297689800,0x00729a5ff800)
allocated by thread T0 here:
    #0 0x731e0bb4a4  (/system/lib64/libclang_rt.asan-aarch64-android.so+0xa24a4)
    #1 0x5b371879f8  (/data/local/tmp/testbed+0x209f8)
    #2 0x731dc6a054  (/apex/com.android.runtime/lib64/bionic/libc.so+0x85054)
    #3 0x5b3717704c  (/data/local/tmp/testbed+0x1004c)
    #4 0x731f657d24  (/data/local/tmp/testbed+0x4cd24)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/data/local/tmp/testbed+0x25a8c) 
Shadow bytes around the buggy address:
  0x001e534bfeb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001e534bfec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001e534bfed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001e534bfee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001e534bfef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x001e534bff00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x001e534bff10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x001e534bff20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x001e534bff30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x001e534bff40: fa fa fa fa fa fa fa fa  [...]

2021-07-10 13:44 UTC, zchrissirhcz commented
https://github.com/Tencent/ncnn/blob/927e34278c30338d4785e78c299b73abf796efc4/src/mat_pixel.cpp#L2064

Note here, if `nn` is initialized as `1`, then `vld1.u8    {d2}, [%3]!` cause invalid read, since we have already read got one `d2` before the `0` labeled loop.

2021-07-10 13:45 UTC, zchrissirhcz commented
看起来是因为要流水线重排，但是 bne 之前多读了一次，在最后一次读取时会发生读越界。
然而 arm32 开 ASan 没有报告，arm64 报出来的。
感觉安全起见还是要改掉。

2021-07-10 15:25 UTC, zchrissirhcz commented
CI failed on windows-x64-cpu-vs2019  (也就是 SSE2 的情况) 的 `test_padding`

```
cmake -DProtobuf_INCLUDE_DIR="$env:GITHUB_WORKSPACE\protobuf-install\include" -DProtobuf_LIBRARIES="$env:GITHUB_WORKSPACE\protobuf-install\lib\libprotobuf.lib" -DProtobuf_PROTOC_EXECUTABLE="$env:GITHUB_WORKSPACE\protobuf-install\bin\protoc.exe" -DNCNN_RUNTIME_CPU=OFF -DNCNN_AVX2=OFF -DNCNN_BUILD_TESTS=ON ..
```

但本地用同一个 commit ，同样的 cmake 参数编译和跑 `test_padding` , 并没有失败。

2021-07-11 06:33 UTC, nihui commented
> CI failed on windows-x64-cpu-vs2019 (也就是 SSE2 的情况) 的 `test_padding`
> 
> ```
> cmake -DProtobuf_INCLUDE_DIR="$env:GITHUB_WORKSPACE\protobuf-install\include" -DProtobuf_LIBRARIES="$env:GITHUB_WORKSPACE\protobuf-install\lib\libprotobuf.lib" -DProtobuf_PROTOC_EXECUTABLE="$env:GITHUB_WORKSPACE\protobuf-install\bin\protoc.exe" -DNCNN_RUNTIME_CPU=OFF -DNCNN_AVX2=OFF -DNCNN_BUILD_TESTS=ON ..
> ```
> 
> ~但本地用同一个 commit ，同样的 cmake 参数编译和跑 `test_padding` , 并没有失败。~
> 本地 Debug 不会 fail， Release 模式也不会 fail，比较奇怪。
> 
> 本地 VS2019 版本为 Community 16.9.0。 现在尝试更新到最新版本。CI中用的是 Enterprise 16.10.31410.357。
> （[https://github.com/actions/virtual-environments/blob/win19/20210628.1/images/win/Windows2019-Readme.md）](https://github.com/actions/virtual-environments/blob/win19/20210628.1/images/win/Windows2019-Readme.md%EF%BC%89)
> 
> UPD: 本地 VS2019 Community 更新到最新版 16.10.3 ， 依然无法复现 CI 中 test_padding 失败的问题。

这好像是 github ci 的问题...

2021-07-11 09:55 UTC, nihui requested changes

2021-07-11 09:55 UTC, nihui commented on src/mat_pixel.cpp
>                  "vsub.s8    d2, d2, %12         \n"
vsub 可以去掉

2021-07-11 09:55 UTC, nihui commented on src/mat_pixel.cpp
>                  "vsub.s8    d2, d2, %12         \n"
同上

2021-07-11 13:54 UTC, merged

2021-07-11 13:54 UTC, nihui commented
Thanks for your contribution !