Fix Innerproduct gemm forgot to add an offset of w in int8 forward
Tencent/ncnn pull request #3084
Opened 2021-07-15 11:19 UTC by lsdustc

gemm need plus a offset after calculated one output

2021-07-16 03:12 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3084) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3084) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: lsdustc<br/>:x: Your Name<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=3084) it.</sub>

2021-07-19 07:09 UTC, nihui requested changes

2021-07-19 07:09 UTC, nihui commented on src/layer/innerproduct.cpp
> +                const char* kptr = (const char*)weight_data + w * p;
signed char

2021-07-19 07:47 UTC, merged

2021-07-19 07:47 UTC, nihui commented
Thanks for your contribution !