Update faq.md
Tencent/ncnn pull request #3332
Opened 2021-11-08 08:41 UTC by luqiang-guo

![4REO97(8 X`%00N(O{XW`_C](https://user-images.githubusercontent.com/9412577/140710322-0b3c5c13-be0b-4f4c-aa64-586bfd166bb7.png)

2021-11-08 09:48 UTC, nihui requested changes

2021-11-08 09:48 UTC, nihui commented on docs/faq.md
> +   自己添加softmax层时，需要加入1=1
in english

2021-11-08 10:00 UTC, luqiang-guo commented on docs/faq.md
> +   自己添加softmax层时，需要加入1=1
It has been modified

2021-11-09 02:27 UTC, merged

2021-11-09 02:27 UTC, nihui approved these changes

2021-11-09 02:27 UTC, nihui commented
Thanks for your contribution !