improvement(binaryop_x86): use std::move and MAKE_FUNCTION macro
Tencent/ncnn pull request #3559
Opened 2022-02-12 05:46 UTC by tpoisonooo

* use `std::move` to optimize memory use,  save  20 bytes per function
* add `MAKE_FUNCTION` macro to simplify function declaration

2022-02-12 05:49 UTC, tpoisonooo commented
这个改法能接受么？ 能的话我把 risc-v 和 arm 的也改了。

2022-02-12 09:01 UTC, tpoisonooo commented
俺没有要改的了。

2022-02-12 15:00 UTC, tpoisonooo commented
> x86 arm pack8 部分也可以改成宏吧 `#define MAKE_FUNCTION(NAME, IMPL)` 分化成 MAKE_FUNCTION_PACK4，MAKE_FUNCTION_PACK8，MAKE_FUNCTION_FP16_PACK8 ..... 这样？

应该 CI 能过。  写的有 `#undef`，就全都是 `MAKE_FUNCTION` ，函数名体现是 pack8 还是 pack4 的。

2022-02-13 05:16 UTC, tpoisonooo commented
好了，搜了一下 rsicv 没漏的。

2022-02-14 06:05 UTC, tpoisonooo commented
一共改了这些版本的 binaryop
arm 	fp32pack4/fp32/fp16pack8/fp16pack4/fp16  
mips	fp32pack4
riscv	fp32/fp16 
x86	        pack8/pack4

* arm 1 处强制类型转换改 `static_cast<float>`
* 所有遇到的 const float & 改 const float，reference 在这里是多余的

2022-02-14 06:18 UTC, nihui requested changes
```x* y``` 改成 ```x * y```

2022-02-14 06:23 UTC, tpoisonooo commented
改完之后， code-format CI 又改成了 `x* y`.... 不行。

2022-02-14 07:29 UTC, nihui commented
> 改完之后， code-format CI 又改成了 `x* y`.... 不行。

```
// clang-format off
// *INDENT-OFF*
your awesome code not intended to be formated ....
// *INDENT-ON*
// clang-format on
```

2022-02-14 12:01 UTC, tpoisonooo commented
改好了。

2022-02-15 02:23 UTC, nihui approved these changes

2022-02-15 02:23 UTC, merged

2022-02-15 02:23 UTC, nihui commented
Thanks for your contribution !