[Gelu x86] Finish intrinsic with elempack merged(fast version)
Tencent/ncnn pull request #4144
Opened 2022-08-15 15:27 UTC by LRY89757

* 实现了Gelu的x86平台优化
* 使用了fast gelu版本，也就是近似版本的`erfc`:
![image](https://user-images.githubusercontent.com/77330637/184664858-2bcb2335-e50e-488d-872c-8a7d74a68a15.png)
* 添加了`tanh`的mathfunc `sse/avx/avx512`实现
* 添加了`test_sample`追求覆盖率.

2022-08-16 13:04 UTC, LRY89757 commented
1. 请教一个问题，关于`mathfun.h`这里的定义宏，为什么要这么定义一个这样的宏：
```c++
/* declare some AVX constants -- why can't I figure a better way to do that? */
#define _PS512_CONST(Name, Val) \
    static const ALIGN64_BEG float _ps512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
#define _PI32_CONST512(Name, Val) \
    static const ALIGN64_BEG int _pi32_512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
#define _PS512_CONST_TYPE(Name, Type, Val) \
    static const ALIGN64_BEG Type _ps512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
```
不应该直接使用`_mm_set1_ps`这类函数就可以了吗？是有着什么更深的用意吗？

2. 关于`tanh`的实现这里暂时借用了`exp`，单独专门的`simd x86`优化正在做**[WIP]**

2022-08-16 14:09 UTC, LRY89757 commented
实现了`tanh`的fast impl版本

2022-09-17 04:23 UTC, nihui requested changes

2022-09-17 04:23 UTC, nihui commented on src/layer/x86/gelu_x86.h
> +// Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
2022

2022-09-17 04:23 UTC, nihui commented on src/layer/x86/gelu_x86.cpp
> +// Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
2022

2022-09-17 04:23 UTC, nihui commented on src/layer/x86/gelu_x86.cpp
> +{
as the non-fast path is not implemented

- disable support_packing based on ```fast_gelu``` value in create_pipeline()
- return ```GELU::forward``` if fast_gelu is zero

2022-09-17 04:23 UTC, nihui commented on src/layer/x86/gelu_x86.cpp
> +        __m256 _fast2c256 = _mm256_set1_ps(0.044715f);
move these constants to later block for better readability  :P

2022-09-17 04:29 UTC, nihui commented
> 1. 请教一个问题，关于`mathfun.h`这里的定义宏，为什么要这么定义一个这样的宏：
> 
> 
> ```c++
> /* declare some AVX constants -- why can't I figure a better way to do that? */
> #define _PS512_CONST(Name, Val) \
>     static const ALIGN64_BEG float _ps512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
> #define _PI32_CONST512(Name, Val) \
>     static const ALIGN64_BEG int _pi32_512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
> #define _PS512_CONST_TYPE(Name, Type, Val) \
>     static const ALIGN64_BEG Type _ps512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
> ```
> 
> 不应该直接使用`_mm_set1_ps`这类函数就可以了吗？是有着什么更深的用意吗？
> 
>     2. ~关于`tanh`的实现这里暂时借用了`exp`， 非常naive的一种实现，单独专门的`simd x86`优化正在做 **[WIP]**~（已实现）

这可能得请教原作者，目前的写法很可能是与编译器斗智斗勇的结果

猜测
* __m256 这样的寄存器无法写作全局静态的变量，结局就是编译器把这些数值放在全局静态区中，运行时载入
* 编译器可能会不对齐的存放数据，于是作者干脆直接写成数组，并强制要求对齐，提升运行时载入效率

2022-09-17 06:35 UTC, LRY89757 commented
> > 1. 请教一个问题，关于`mathfun.h`这里的定义宏，为什么要这么定义一个这样的宏：
> > 
> > ```c++
> > /* declare some AVX constants -- why can't I figure a better way to do that? */
> > #define _PS512_CONST(Name, Val) \
> >     static const ALIGN64_BEG float _ps512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
> > #define _PI32_CONST512(Name, Val) \
> >     static const ALIGN64_BEG int _pi32_512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
> > #define _PS512_CONST_TYPE(Name, Type, Val) \
> >     static const ALIGN64_BEG Type _ps512_##Name[16] ALIGN64_END = {Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val, Val}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不应该直接使用`_mm_set1_ps`这类函数就可以了吗？是有着什么更深的用意吗？
> > ```
> > 2. ~关于`tanh`的实现这里暂时借用了`exp`， 非常naive的一种实现，单独专门的`simd x86`优化正在做 **[WIP]**~（已实现）
> > ```
> 
> 这可能得请教原作者，目前的写法很可能是与编译器斗智斗勇的结果
> 
> 猜测
> 
> * __m256 这样的寄存器无法写作全局静态的变量，结局就是编译器把这些数值放在全局静态区中，运行时载入
> * 编译器可能会不对齐的存放数据，于是作者干脆直接写成数组，并强制要求对齐，提升运行时载入效率

Got it, thanks for guidance. I will improve the codes as soon as possible.

2022-09-17 08:16 UTC, LRY89757 commented
> 已经按照对应的指导改正代码格式，同时也修正添加了create_pipeline函数用来回退版本

有一个进一步问题，既然我此前x86simd端全部使用的是fast_gelu用来计算的同时test函数并没有报错，是否这意味着我们没有必要使用erfc来进行推理而直接全部使用fast_gelu版本来进行计算即可，因为两者计算出来的结果几乎没有误差？

2022-09-17 08:58 UTC, nihui commented
> > 已经按照对应的指导改正代码格式，同时也修正添加了create_pipeline函数用来回退版本
> 
> 有一个进一步问题，既然我此前`x86` `simd`代码全部使用的是`fast_gelu`用来计算，同时test函数并没有报错，是否这意味着我们没有必要使用`erfc`来进行推理而直接全部使用`fast_gelu`版本来进行计算即可，因为两者计算出来的结果几乎没有误差？ 如果有必要的话我会把`simd`版本的`erfc`加上去

没有必要，erfc 在 naive 实现里面就足够了，为的就是参考一下
目前pnnx那边转出ncnn的gelu一律会设置 fast_gelu=1

2022-09-18 05:07 UTC, merged

2022-09-18 05:07 UTC, nihui commented
Thanks for your contribution !