pretty formatting
Tencent/ncnn pull request #4193
Opened 2022-09-10 20:31 UTC by magicse

changed size of images for pretty formatting of page.

2022-09-13 04:40 UTC, nihui requested changes

2022-09-13 04:40 UTC, nihui commented on README.md
> +功能概述
messed text ?

2022-09-13 13:08 UTC, magicse commented on README.md
> +功能概述
Hi Nihui. Images was so big and not beauty formatted before. 
Now images will be in one line.

2022-09-15 05:42 UTC, nihui commented on README.md
> +功能概述
yeah, but '功能概述' is redundant here

2022-09-15 11:40 UTC, magicse commented on README.md
> +功能概述
Yes sure it could be removed

2022-09-15 22:22 UTC, nihui approved these changes

2022-09-15 22:26 UTC, merged

2022-09-15 22:26 UTC, nihui commented
Thanks for your contribution !