Update VF2 score
Tencent/ncnn pull request #4688
Opened 2023-05-03 13:47 UTC by MobtgZhang

Update VisionFive2 JH7110 score(riscv64)

2023-05-03 13:47 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4688) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4688) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4688) it.</sub>

2023-05-04 07:19 UTC, nihui requested changes

2023-05-04 07:19 UTC, nihui commented on benchmark/README.md
> +
remove unrelated space changes

2023-05-05 10:38 UTC, merged

2023-05-05 10:39 UTC, nihui commented
Thanks for your contribution !