Don't silently ignore errors in VkCompute::submit_and_wait
Tencent/ncnn pull request #4769
Opened 2023-05-31 11:55 UTC by Upliner

We had a problem when there was "vkQueueSubmit failed" error printed in console but ncnn::Extractor::extract doesn't return any error because return value of submit_and_wait isn't checked.

2023-05-31 11:55 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4769) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4769) it.</sub>

2023-06-12 08:36 UTC, nihui requested changes

2023-06-12 08:36 UTC, nihui commented on src/gpu.cpp
> +    return cmd.submit_and_wait();
The callee returned a possible error, but the caller did not handle it

2023-06-12 08:36 UTC, nihui commented on src/net.cpp
> +    return cmd.submit_and_wait();
The callee returned a possible error, but the caller did not handle it

2023-06-12 08:36 UTC, nihui commented on src/net.cpp
> +
remove the blank line

2023-06-12 08:36 UTC, nihui commented on src/net.cpp
> +            int ret;
the ret variable is already declared earlier. this line is not necessary.

2023-06-29 16:57 UTC, closed without merging