feat(benchmark/benchncnn.cpp): support user defined case
Tencent/ncnn pull request #4782
Opened 2023-06-06 03:59 UTC by tpoisonooo

`benchncnn` 支持指定 param 文件
1. 不指定保持原行为
2. 输入错误打印 usage

```bash
$ ./benchncnn 20 1 1 -1 1 /home/khj/ncnn/benchmark/squeezenet.param  227 227 3
loop_count = 20
num_threads = 1
powersave = 1
gpu_device = -1
cooling_down = 1
/home/khj/ncnn/benchmark/squeezenet.param  min =    5.90  max =    7.86  avg =    6.23
```

```bash
$ ./benchncnn                                                                 
Usage: benchncnn loop thread_num powersave gpu_device cooling_down [model w h c]
```

2023-06-06 07:43 UTC, tpoisonooo commented
https://platform.openmmlab.com/deploee  硬件测速，加了个直接测试  .param 速度。
里面 ncnn 用的这个。

![图片](https://github.com/Tencent/ncnn/assets/7872421/9a89ea46-8279-41ab-9c8b-139c8b41c2e7)

2023-06-06 08:32 UTC, tpoisonooo commented
rebase 一下 master. done.

2023-06-12 08:45 UTC, nihui commented
参考 pnnx main.cpp，额外的高级参数采用 [(key=value)...] 的形式，有更好的扩展性

```
./benchncnn 20 1 1 -1 1
./benchncnn 20 1 1 -1 1 param=/home/khj/ncnn/benchmark/squeezenet.param shape=[227,227,3]
```

2023-06-15 05:43 UTC, tpoisonooo commented
done.

2023-07-13 07:30 UTC, tpoisonooo commented
@nihui  每日一催

2023-07-18 08:21 UTC, tpoisonooo commented
@nihui 每周一催

2023-07-20 03:01 UTC, nihui requested changes

2023-07-20 03:01 UTC, nihui commented on benchmark/benchncnn.cpp
> +    char* model = nullptr;
= 0

2023-07-20 03:01 UTC, nihui commented on benchmark/benchncnn.cpp
> +    if (model != nullptr && inputs.empty())
model && inputs.empty()

2023-08-09 07:52 UTC, tpoisonooo commented on benchmark/benchncnn.cpp
> +                in.fill(0.01f);
我理解是要删掉？ 删掉了。

2023-08-09 07:52 UTC, tpoisonooo commented on benchmark/benchncnn.cpp
> +            ex.extract(output_names[0], out);
done.

2023-08-09 07:53 UTC, tpoisonooo commented on benchmark/benchncnn.cpp
> +    char* model = nullptr;
done.

2023-08-09 07:53 UTC, tpoisonooo commented on benchmark/benchncnn.cpp
> +        benchmark("squeezenet", {ncnn::Mat(227, 227, 3)}, opt);
done.

2023-08-09 07:53 UTC, tpoisonooo commented
@nihui  每月一催

2023-08-10 08:05 UTC, tpoisonooo commented
@nihui 日催

2023-08-11 03:17 UTC, merged

2023-08-11 03:17 UTC, nihui commented
Thanks for your contribution !

@tpoisonooo  合并啦！