WIP: add riscv gemm
Tencent/ncnn pull request #4903
Opened 2023-08-03 02:56 UTC by Xinyu302

2023-08-03 02:57 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4903) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4903) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4903) it.</sub>

2023-08-10 02:44 UTC, nihui commented
期待你的 riscv gemm ！这个任务挺难的（

2023-08-21 06:50 UTC, Xinyu302 commented
仿照arm64版本的gemm，有了一个float32的基本实现，可以通过test_gemm和test_gemm1的测试。
由于riscv向量化里面没有zip，transpose*系列函数做了基本的实现。
同时riscv里面也没有vst2q，vst4q这种StoreZipFloat的指令，仅弄了一个能用的实现。

2023-09-13 10:54 UTC, nihui requested changes
很多intrinsics在新的gcc中无法编译了，这里需要兼容，具体看下ci中的错误

2023-09-15 03:08 UTC, nihui commented
nT 初始化成了随机数？

2023-09-15 11:09 UTC, Xinyu302 commented
> nT 初始化成了随机数？

忘了初始化了QAQ

2023-09-15 11:10 UTC, Xinyu302 commented
修改了一些intrinsic，现在去掉C906的宏也可以在linux-gcc-riscv64-rvv的编译环境下编译了，不知道其它环境下会不会炸.

2023-09-15 11:16 UTC, Xinyu302 commented
现在的默认硬件是128向量寄存器，所以VL是4。如何硬件是256位的，VL=8，感觉整个向量化代码的部分都需要重写。

2023-09-15 11:19 UTC, nihui commented
> 现在的默认硬件是128向量寄存器，所以VL是4。如何硬件是256位的，VL=8，感觉整个向量化代码的部分都需要重写。

VL=8 的硬件还不存在，感觉可以暂时搁置（（

以及，这个优化后，gemm 在 c906 上的性能提升如何，有测试数据吗，比如构造一个只有gemm层的模型跑

2023-09-16 07:04 UTC, Xinyu302 commented
> > 现在的默认硬件是128向量寄存器，所以VL是4。如何硬件是256位的，VL=8，感觉整个向量化代码的部分都需要重写。
> 
> VL=8 的硬件还不存在，感觉可以暂时搁置（（
> 
> 以及，这个优化后，gemm 在 c906 上的性能提升如何，有测试数据吗，比如构造一个只有gemm层的模型跑

我发现我不太会构建一个只有gemm层的模型，可以直接魔改test里面的test_gemm吗，加一些计时代码。
另外code-format这个ci的报错是什么意思呀？

2023-09-16 11:58 UTC, nihui commented
code-format 需要 https://github.com/Xinyu302/ncnn/actions  fork repo 启用 github action

2023-09-16 12:01 UTC, nihui commented
模型可以参考 tools/pnnx/tests/ncnn/test_torch_mm.py 这样构建，然后 pnnx 转出来

2023-09-16 18:02 UTC, Xinyu302 commented
> code-format 需要 https://github.com/Xinyu302/ncnn/actions fork repo 启用 github action

已经开启了

2023-09-16 18:08 UTC, Xinyu302 commented
> 模型可以参考 tools/pnnx/tests/ncnn/test_torch_mm.py 这样构建，然后 pnnx 转出来



> 模型可以参考 tools/pnnx/tests/ncnn/test_torch_mm.py 这样构建，然后 pnnx 转出来

在https://github.com/Xinyu302/ncnn/tree/gemm-time-test中，首先加入了matmul_riscv.cpp，然后使用pnnx构建了一个只有matmul的模型，但是测试时好像没有正确调用到gemm层，报了Segmentation fault，原因是没有执行MatMul_riscv::create_pipeline，gemm是空指针，有点不理解.

2023-09-17 19:33 UTC, Xinyu302 commented
qemu的时间也太不准了啊...
用全志D1测 m=n=k，naive没有优化，tile只分块没有向量化，vectorize使用向量化，单位微秒
|      | naive                           | tile    | vectorize |
| ---- | ------------------------------- | ------- | --------- |
| 32   | 309 | 229     | 355       |
| 128  | 17079                           | 8019    | 5280      |
| 512  | 1010970                         | 466917  | 211145    |
| 1024 | 7826209                         | 3556337 | 1576699   |

2023-09-20 04:32 UTC, Xinyu302 commented on src/layer/riscv/riscv_usability.h
> +#define VL 4
transpose8x8_ps和transpose4x4_ps的情况好像确实可以这样做

2023-09-20 04:33 UTC, Xinyu302 commented on src/layer/riscv/gemm_riscv.cpp
> +int Gemm_riscv::create_pipeline(const Option& opt)
vlen超过128bit的情况，仍然使用VL=4也不会出问题吧

2023-09-20 06:25 UTC, nihui commented on src/layer/riscv/gemm_riscv.cpp
> +int Gemm_riscv::create_pipeline(const Option& opt)
> vlen超过128bit的情况，仍然使用VL=4也不会出问题吧

是的，qemu 256bit 测试是通过的！不过浪费了些256bit的计算，可以加些注释说明一下

2023-09-20 06:44 UTC, Xinyu302 commented on src/layer/riscv/riscv_usability.h
> +#define VL 4
这个还没修，有时间了再改一下

2023-09-20 07:16 UTC, Xinyu302 commented on src/layer/riscv/gemm_riscv.cpp
> +int Gemm_riscv::create_pipeline(const Option& opt)
要求transpose之后向量寄存器要存到的内存是连续的，这样就可以不用transpose8x8_ps里面的tmp数组了，但是看了一下gemm中现有的transpose满足这个条件的并不多。

2023-09-20 07:17 UTC, Xinyu302 commented on src/layer/riscv/riscv_usability.h
> +#define VL 4
要求transpose之后向量寄存器要存到的内存是连续的，这样就可以不用transpose8x8_ps里面的tmp数组了，但是看了一下gemm中现有的transpose满足这个条件的并不多。要求transpose之后向量寄存器要存到的内存是连续的，这样就可以不用transpose8x8_ps里面的tmp数组了，但是看了一下gemm中现有的transpose满足这个条件的并不多。

2023-09-21 06:06 UTC, nihui commented
如果自认为完成，请去掉标题的 WIP

2023-09-21 12:17 UTC, Xinyu302 commented
> 如果自认为完成，请去掉标题的 WIP

其实还有fp16的gemm没做，但是最近这两天又比较忙，想等到周末再看一下。

2023-09-22 11:32 UTC, Xinyu302 commented
> 如果自认为完成，请去掉标题的 WIP

没有在riscv中找到与vfmlalq_laneq_low_f16类似的f16乘f16最后和f32累加的intrinsic函数。在计算前先讲f32转换成f16，如果还是需要在运算时将f16转换成f32，那么这样做能取得足够的收益吗？

2023-09-23 03:58 UTC, nihui commented
> > 如果自认为完成，请去掉标题的 WIP
> 
> 没有在riscv中找到与vfmlalq_laneq_low_f16类似的f16乘f16最后和f32累加的intrinsic函数。在计算前先讲f32转换成f16，如果还是需要在运算时将f16转换成f32，那么这样做能取得足够的收益吗？

vfwmul_vf_f32m2

可以参考 convolution_packn_fp16s.h fp16s部分写法

2023-09-26 06:34 UTC, Xinyu302 commented
> > > 如果自认为完成，请去掉标题的 WIP
> > 
> > 
> > 没有在riscv中找到与vfmlalq_laneq_low_f16类似的f16乘f16最后和f32累加的intrinsic函数。在计算前先讲f32转换成f16，如果还是需要在运算时将f16转换成f32，那么这样做能取得足够的收益吗？
> 
> vfwmul_vf_f32m2
> 
> 可以参考 convolution_packn_fp16s.h fp16s部分写法

国庆之前估计没时间写了，放假的时候应该可以搞一下，完成“利用risc-v vector和zfh(fp16)扩展优化实现gemm_riscv.cpp，使用qemu测试”的目标

2023-10-16 03:02 UTC, nihui approved these changes

2023-10-16 03:03 UTC, nihui approved these changes

2023-10-20 07:43 UTC, merged

2023-10-20 07:43 UTC, nihui commented
Thanks for your contribution !