pnnx convert diag
Tencent/ncnn pull request #4935
Opened 2023-08-11 15:54 UTC by wnqn1597

2023-08-14 09:16 UTC, nihui requested changes

2023-08-14 09:16 UTC, nihui commented on src/CMakeLists.txt
> +ncnn_add_layer(Diag)
append new layer at the last for layer type id compatible

2023-08-14 09:16 UTC, nihui commented on tools/pnnx/src/pass_level2/torch_diag.cpp
> +aten::diag         op_0        2 1 input diagonal out
align spaces

2023-08-14 09:16 UTC, nihui commented on tools/pnnx/src/pass_level2/torch_diag.cpp
> +5 4
4 3 ?

2023-08-14 09:16 UTC, nihui commented on tools/pnnx/src/pass_ncnn/torch_diag.cpp
> +torch.diag           op_0        1 1 input out diagonal=%diagonal
align spaces

2023-08-14 09:17 UTC, nihui requested changes
add pnnx ncnn tests
update docs operators.md

2023-08-24 11:35 UTC, nihui commented
pass_ncnn/torch_diag.cpp doesn't seem to work for some reasons

2023-08-26 13:12 UTC, wnqn1597 commented
> pass_ncnn/torch_diag.cpp doesn't seem to work for some reasons, see pnnx ci errors

Can I take a look at the logs of pnnx ci?

2023-08-28 02:51 UTC, nihui commented
> > pass_ncnn/torch_diag.cpp doesn't seem to work for some reasons, see pnnx ci errors
> 
> Can I take a look at the logs of pnnx ci?

click into pnnx ci, login with your github, and you could see the log there

2023-08-28 02:52 UTC, nihui commented
```
 446/507 Test #450: test_ncnn_torch_diag ..........................***Failed    5.55 sec
pnnxparam = test_torch_diag.pnnx.param
pnnxbin = test_torch_diag.pnnx.bin
pnnxpy = test_torch_diag_pnnx.py
pnnxonnx = test_torch_diag.pnnx.onnx
ncnnparam = test_torch_diag.ncnn.param
ncnnbin = test_torch_diag.ncnn.bin
ncnnpy = test_torch_diag_ncnn.py
fp16 = 1
optlevel = 2
device = cpu
inputshape = [7]f32,[5,5]f32,[4,8]f32
inputshape2 = 
customop = 
moduleop = 
############# pass_level0

----------------

############# pass_level1
############# pass_level2
############# pass_level3
############# pass_level4
############# pass_level5
############# pass_ncnn
force batch axis 233 for operand 0
force batch axis 233 for operand 4
force batch axis 233 for operand 3
fallback batch axis 233 for operand 1
fallback batch axis 233 for operand 2
fallback batch axis 233 for operand 5
ignore torch.diag torch.diag_2 param diagonal=3
ignore torch.diag torch.diag_1 param diagonal=0
ignore torch.diag torch.diag_0 param diagonal=-1
layer torch.diag not exists or registered
CMake Error at /data/devops/workspace/tools/pnnx/tests/run_test.cmake:5 (message):
  Test failed with return value 'Segmentation fault'
```

2023-09-08 10:53 UTC, nihui approved these changes

2023-09-08 10:53 UTC, nihui commented
lgtm

2023-09-08 14:01 UTC, merged

2023-09-08 14:01 UTC, nihui commented
Thanks for your contribution !