add F_pairwise_distance to pnnx  and ncnn
Tencent/ncnn pull request #4942
Opened 2023-08-14 08:52 UTC by Marsyule

2023-08-14 08:52 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4942) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4942) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4942) it.</sub>

2023-08-24 02:32 UTC, nihui commented
hi, please enable github action in your forked repo, to let code-format job work properly

2023-09-04 03:09 UTC, nihui commented
please fix ci error
```
  36/506 Test  #50: test_F_pairwise_distance ......................***Failed    0.06 sec
  File "/data/devops/workspace/tools/pnnx/tests/test_F_pairwise_distance.py", line 52
    return torch.equal(a0,b0) and torch.equal(a1,b1) and torch.equal(a2,b2) and torch.equal(a3,b3)
IndentationError: unexpected indent
CMake Error at /data/devops/workspace/tools/pnnx/tests/run_test.cmake:5 (message):
  Test failed with return value '1'

```

2023-09-14 15:55 UTC, nihui requested changes
overall it looks good besides some space style issues

2023-09-14 15:55 UTC, nihui commented on tools/pnnx/src/pass_ncnn/F_pairwise_distance.cpp
There isn't a ncnn layer called PairwiseDistance.
Either implement the layer or drop the ncnn conversion and leave pnnx conversion only.

If you plan to implement the ncnn layer later, add the ncnn conversion at that time.

2023-09-14 15:55 UTC, nihui commented on tools/pnnx/src/CMakeLists.txt
> +	pass_level2/F_pairwise_distance.cpp
space instead of tab

2023-09-14 15:55 UTC, nihui commented on tools/pnnx/src/CMakeLists.txt
> +	pass_ncnn/F_pairwise_distance.cpp
space instead of tab

2023-09-14 15:55 UTC, nihui commented on tools/pnnx/src/pass_level2/F_pairwise_distance.cpp
> +aten::pairwise_distance op_3     	5 1 x1 x2 p eps keepdim out
align spaces

2023-09-21 02:34 UTC, nihui requested changes

2023-09-21 02:34 UTC, nihui commented on tools/pnnx/src/pass_ncnn/F_pairwise_distance.cpp
remove this source as no such ncnn layer exists

2023-09-22 02:38 UTC, nihui approved these changes

2023-09-22 07:27 UTC, merged

2023-09-22 07:27 UTC, nihui commented
Thanks for your contribution !