add gelu vulkan operator
Tencent/ncnn pull request #5001
Opened 2023-09-03 08:28 UTC by FhqTreap

add gelu vulkan operator

2023-09-04 03:17 UTC, nihui approved these changes
lgtm

2023-09-04 04:32 UTC, nihui requested changes

2023-09-04 04:32 UTC, nihui commented on src/layer/vulkan/gelu_vulkan.h
> +#endif // LAYER_ELU_VULKAN_H
```suggestion
#endif // LAYER_GELU_VULKAN_H
```

2023-09-04 09:17 UTC, merged

2023-09-04 09:17 UTC, nihui commented
Thanks for your contribution !

2023-09-04 17:01 UTC, DickyQi commented
for MacOS with vulkan fp16 build failed.

2023-09-05 02:52 UTC, FhqTreap commented
> for MacOS with vulkan fp16 build failed.

more details on this?😮

2023-09-05 04:56 UTC, nihui commented
> > for MacOS with vulkan fp16 build failed.
> 
> more details on this?😮

tanh fp16 on moltenvk has precision issue, so it is banned on half values

workaround follows (ref tanh comp)

```
#if NCNN_moltenvk
    v = afpvec4(tanh(vec4(v)));
#else
    v = tanh(v);
#endif
```

2023-09-05 05:07 UTC, FhqTreap commented
> > > for MacOS with vulkan fp16 build failed.
> > 
> > 
> > more details on this?😮
> 
> tanh fp16 on moltenvk has precision issue, so it is banned on half values
> 
> workaround follows (ref tanh comp)
> 
> ```
> #if NCNN_moltenvk
>     v = afpvec4(tanh(vec4(v)));
> #else
>     v = tanh(v);
> #endif
> ```

so it shuold look like this?

```
#if NCNN_moltenvk
    v = 0.5f * v * (1.0f + afp(tanh(float(0.79788452f * (v + 0.044715f * v * v * v)))));
#else
    v = 0.5f * v * (1.0f + tanh(0.79788452f * (v + 0.044715f * v * v * v)));
#endif
```

2023-09-05 05:10 UTC, FhqTreap commented
> > > for MacOS with vulkan fp16 build failed.
> > 
> > 
> > more details on this?😮
> 
> tanh fp16 on moltenvk has precision issue, so it is banned on half values
> 
> workaround follows (ref tanh comp)
> 
> ```
> #if NCNN_moltenvk
>     v = afpvec4(tanh(vec4(v)));
> #else
>     v = tanh(v);
> #endif
> ```

so it shuold look like this?

```
#if NCNN_moltenvk
    v = 0.5f * v * (1.0f + afp(tanh(float(0.79788452f * (v + 0.044715f * v * v * v)))));
#else
    v = 0.5f * v * (1.0f + tanh(0.79788452f * (v + 0.044715f * v * v * v)));
#endif
```

2023-09-05 05:33 UTC, nihui commented
> > > > for MacOS with vulkan fp16 build failed.
> > > 
> > > 
> > > more details on this?😮
> > 
> > 
> > tanh fp16 on moltenvk has precision issue, so it is banned on half values
> > workaround follows (ref tanh comp)
> > ```
> > #if NCNN_moltenvk
> >     v = afpvec4(tanh(vec4(v)));
> > #else
> >     v = tanh(v);
> > #endif
> > ```
> 
> so it shuold look like this?
> 
> ```
> #if NCNN_moltenvk
>     v = 0.5f * v * (1.0f + afp(tanh(float(0.79788452f * (v + 0.044715f * v * v * v)))));
> #else
>     v = 0.5f * v * (1.0f + tanh(0.79788452f * (v + 0.044715f * v * v * v)));
> #endif
> ```

yeah, exactly