Improve cmake toolchain files
Tencent/ncnn pull request #5144
Opened 2023-11-11 13:58 UTC by zchrissirhcz

A cleanup of `toolchains` directory's cmake files:
- Use `set` instead of `SET `
- Specify `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE`'s value
- Provide default values for `CMAKE_FIND_ROOT_PATH_MODE_{PROGRAM,LIBRARY,INCLUDE,PACKAGE}`, allow user to overwrite them in cmake command args
- Indent with 2 spaces in affected files

Related reference: https://github.com/android/ndk/issues/517

The PR is divided into 4 commits but can be squashed into one if is agreed to be merged.

2023-11-11 14:13 UTC, zchrissirhcz commented
force pushed due to submodules mis-added in previous push.

2023-11-13 06:37 UTC, nihui requested changes
Use 4 spaces for indentation

2023-11-13 08:08 UTC, nihui approved these changes

2023-11-13 09:25 UTC, merged

2023-11-13 09:25 UTC, nihui commented
Thanks for your contribution !