Fix BOF in the last channel handling logic of SSE ShuffleChannel
Tencent/ncnn pull request #5735
Opened 2024-10-14 22:48 UTC by junwha

Fix https://github.com/Tencent/ncnn/issues/5734

- apply SSE logic until size-1
- apply linear logic for the last n elements

2024-10-14 22:48 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5735) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5735) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=5735) it.</sub>

2024-10-17 07:04 UTC, nihui requested changes

2024-10-17 07:04 UTC, nihui commented on src/layer/x86/shufflechannel_x86.cpp
> +                }
I don't think there is a risk of out of range reading in some of the pack8/pack16 codes.

2024-10-17 07:04 UTC, nihui commented on src/layer/arm/shufflechannel_arm.cpp
> +                }
unroll this

2024-10-17 07:04 UTC, nihui commented on src/layer/x86/shufflechannel_x86.cpp
> +                }
I don't think there is a risk of out of range reading in some of the pack8/pack16 codes.

2024-10-17 07:04 UTC, nihui commented on src/layer/arm/shufflechannel_arm.cpp
> +                }
I don't think there is a risk of out of range reading in some of the arm pack8 codes.

2024-10-17 07:04 UTC, nihui commented on src/layer/arm/shufflechannel_arm.cpp
> +                }
unroll this

2024-10-18 06:40 UTC, junwha commented
Hi @nihui,
Thank you for the fast response and review!
I will reflect the unrolling.

Could I ask why do you think the out-of-bound risk does not exist in pack8/16 codes?
As far as I think, it also accesses (start of the channel) + (size-1)*(element size) + (element size)/2 in the same manner, which is beyond the size of the channel.

Thank you for your effort on this issue!

2026-05-09 02:37 UTC, nihui approved these changes

2026-05-09 03:45 UTC, merged

2026-05-09 03:45 UTC, nihui commented
Thanks for your contribution !