Fix #5741 don't crash when vkCreateDevice fails
Tencent/ncnn pull request #5742
Opened 2024-10-17 00:21 UTC by Upliner

This patch should fix #5741 and prevent crash if vkCreateDevice fails or unable to create dummy buffer image.

2024-10-17 00:21 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5742) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5742) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=5742) it.</sub>

2024-10-17 07:57 UTC, nihui requested changes

2024-10-17 07:57 UTC, nihui commented on src/net.cpp
> +        if (!d->vkdev || !d->vkdev->is_valid()) opt.use_vulkan_compute = false; // no valid vulkan device, fallback to cpu
and apply this change to `Net::load_param_bin` too

2024-10-18 02:23 UTC, nihui approved these changes

2024-10-18 02:23 UTC, merged

2024-10-18 02:24 UTC, nihui commented
Thanks for your contribution !